#!/usr/bin/env bash
set -euo pipefail

build_zip_archive () {
    PLATFORM_NAME="$1"
    REGULAR_MANIFEST_PATH="./public/manifest.json"
    ZIP_NAME="$PLATFORM_NAME.zip"
    MANIFEST_PATH="./public/$2"
    ICON="$3"

    if [ ! -f "$MANIFEST_PATH" ]; then
        echo "Manifest file `$MANIFEST_PATH` not found for $PLATFORM_NAME!"
        return
    fi

    # Rename versionaled manifest to a regular manifest.json
    mv "$MANIFEST_PATH" "$REGULAR_MANIFEST_PATH"

    podman-compose exec app npm run build

    cd dist && zip -r ../"$ZIP_NAME" . && cd -

    # Rename regular manifest.json back to a versioned
    mv "$REGULAR_MANIFEST_PATH" "$MANIFEST_PATH" 

    echo "$ICON Archive $ZIP_NAME is ready!"
}

build_zip_archive "firefox" "manifest2.json" "🦊"
build_zip_archive "chrome" "manifest3.json" "💩"
